#!/bin/sh
#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc


# >>> juliaup initialize >>>

# !! Contents within this block are managed by juliaup !!

case ":$PATH:" in
    *:/home/ahnafrafi/.juliaup/bin:*)
        ;;

    *)
        export PATH=/home/ahnafrafi/.juliaup/bin${PATH:+:${PATH}}
        ;;
esac

# <<< juliaup initialize <<<
