#!/bin/sh
#
# ~/.bashrc
#

alias ll='ls -alhF --group-directories-first'

# >>> juliaup initialize >>>

# !! Contents within this block are managed by juliaup !!

case ":$PATH:" in
    *:/home/ahnafrafi/.juliaup/bin:*)
        ;;

    *)
        export PATH=/home/ahnafrafi/.juliaup/bin${PATH:+:${PATH}}
        ;;
esac

# <<< juliaup initialize <<<
